name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag for the Docker image'
        required: true
        default: 'latest'

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Quarkus application
        run: |
          cd lambda-pom/quarkus-lambda
          mvn package -DskipTests

      - name: Build Docker image
        run: |
          cd lambda-pom/quarkus-lambda
          docker build -f src/main/docker/Dockerfile.jvm -t ghcr.io/${{ github.repository_owner }}/quarkus-lambda:${{ github.event.inputs.version }} .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/quarkus-lambda:${{ github.event.inputs.version }}

      - name: Summary
        run: |
          echo "## Docker Image Built and Pushed" >> $GITHUB_STEP_SUMMARY
          echo "Image: ghcr.io/${{ github.repository_owner }}/quarkus-lambda:${{ github.event.inputs.version }}" >> $GITHUB_STEP_SUMMARY

