name: Build JVM JAR

on:
  workflow_dispatch:

jobs:
  build:
    name: Build JVM JAR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven (JVM mode)
        run: |
          cd lambda-pom/quarkus-lambda
          mvn package -DskipTests

      - name: Upload quarkus-run.jar
        uses: actions/upload-artifact@v4
        with:
          name: quarkus-run-jar
          path: artifact_dir/quarkus-run.jar
          retention-days: 7

      - name: Upload complete JVM package
        uses: actions/upload-artifact@v4
        with:
          name: quarkus-lambda-jvm-package
          path: artifact_dir/
          retention-days: 7

