name: Build Native Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build Native Executable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Setup GraalVM Community Edition
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm-community'
          components: 'native-image'
          native-image-job-reports: 'true'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify GraalVM version
        run: |
          docker run --rm quay.io/quarkus/ubi-quarkus-mandrel-builder-image:23.1.6.0-Final-java21-arm64 java -version
      - name: Build with Maven and GraalVM Native Image
        run: |
          cd lambda-pom/quarkus-lambda
          docker buildx create --use --platform linux/amd64
          mvn package -Pnative -DskipTests -Dquarkus.native.container-build=true

      - name: Upload native executable
        uses: actions/upload-artifact@v4
        with:
          name: quarkus-lambda-native-executable
          path: lambda-pom/quarkus-lambda/target/*-runner
          retention-days: 7

      - name: Upload function.zip for AWS Lambda
        uses: actions/upload-artifact@v4
        with:
          name: lambda-function-package
          path: lambda-pom/quarkus-lambda/target/function.zip
          retention-days: 7
