name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag for the Docker image'
        required: true
        default: 'latest'

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          cd lambda-pom/quarkus-lambda
          # Override the version tag if provided through workflow dispatch
          mvn package -DskipTests \
            -Dquarkus.container-image.registry=ghcr.io \
            -Dquarkus.container-image.group=${{ github.repository_owner }} \
            -Dquarkus.container-image.tag=${{ github.event.inputs.version || 'latest' }} \
            -Dquarkus.container-image.push=true
            
      - name: Summary
        run: |
          echo "## Docker Image Built and Pushed" >> $GITHUB_STEP_SUMMARY
          echo "Image: ghcr.io/${{ github.repository_owner }}/quarkus-lambda:${{ github.event.inputs.version || 'latest' }}" >> $GITHUB_STEP_SUMMARY
